"""
Exact wire formats for the sealed replay data in this module.

Key derivation
- All three sealers start from a 32-byte root key in `SealingKeyring`.
- For purpose `p`, the working key is:

    HKDF-SHA256(
        root_key,
        salt=None,
        info=b"plap:" + p,
        length=32,
    )

- Purpose strings used here:
  - `responses.ingest.call_id`
  - `responses.ingest.reasoning`
  - `responses.ingest.compaction`

Reasoning and compaction payloads
- Plaintext is deterministic `msgspec` JSON.
- Reasoning envelope:

    {
        "version": 6,
        "type": "reasoning",
        "id": <string>,
        "previous_reasoning_id": <string|null>,
        "previous_compaction_id": <string|null>,
        "state": {
            "type": "checkpoint",
            "durable": <object>,
            "active": [<side>, ...],
            "sides": {
                <non-main-side>: [<message>, ...],
            },
        } | {
            "type": "patch",
            "durable": <JSONPatch>,
            "active": [<side>, ...] | null,
            "sides": {
                <non-main-side>: <JSONPatch>,
            },
        },
        "main": [<message>..., <optional-postfix-message-patch>],
    }

- Compaction envelope:

    {
        "version": 4,
        "type": "compaction",
        "id": <string>,
        "durable": <object>,
        "sides": <Sides>,
    }

- Side snapshot:

    {
        "active": [<side>, ...],
        "messages": {
            <side>: [<message>, ...],
        },
    }

- Reasoning checkpoints replace durable state, active membership, and every non-main
  side. Reasoning patches apply deltas to those fields. Main always uses the
  common append-only `main` lane and is never checkpointed by reasoning.
- `previous_compaction_id` is null before any compaction and otherwise equals
  the latest replayed compaction ID for every checkpoint and patch.

- The JSON bytes are compressed with zstd, then encrypted with
  PyNaCl `nacl.secret.Aead`, which uses XChaCha20-Poly1305-IETF.
- Parameters:
  - key: the 32-byte purpose-derived key
  - AAD: `b"plap:" + purpose`
  - nonce: a random 24-byte nonce generated by `Aead.encrypt()`
- PyNaCl returns the combined blob as:

    nonce[24] || ciphertext[len(compressed)] || tag[16]

- The stored string is unpadded base64url of that combined blob.
- There is no textual prefix for reasoning/compaction strings; only the
  call-id layer adds one.

Sealed call ids
- Text form:

    "call_" + base64url_unpadded(aes_siv_output)

- Before encryption, the plaintext byte layout is:

    header[1]
    || side_code_be_u16[2]
    || encoded_upstream_tool_call_id[bytes]

- `header` bit layout:
  - bits 7..4: format version (`2`)
  - bits 3..2: reserved and must be zero
  - bits 1..0: upstream id codec

- Upstream id codecs:
  - `00 = utf8`
  - `01 = ascii7`
  - `10 = base64url6`
  - `11` is reserved

- `side_code_be_u16` is the side code as an unsigned 16-bit big-endian integer.

 - Side codes come from `config.sides` in the loaded CUE config.
 - Only configured sides may be encoded or decoded.
 - Other `u16` values are unassigned.

- `encoded_upstream_tool_call_id` decodes to the required, non-empty UTF-8
  `upstream_tool_call_id`.
- Packed codecs store:

    packed_meta[1] || packed_bytes[...]

- `packed_meta` bit layout:
  - bits 7..3: reserved and must be zero
  - bits 2..0: unused bits in the final packed byte
- `ascii7` packs one 7-bit ASCII byte per symbol.
- `base64url6` packs one 6-bit symbol per base64url character using alphabet:
  `A-Z a-z 0-9 - _`.

Call-id encryption
- Call-id plaintext is encrypted with `cryptography` `AESSIV`.
- Parameters:
  - key: the 32-byte purpose-derived key
  - associated_data: `[b"plap:responses.ingest.call_id"]`
- No nonce is supplied, so this layer is deterministic AES-SIV.
- `AESSIV.encrypt()` returns:

    siv_tag[16] || ciphertext[len(plaintext)]

- The final external string is the `"call_"` prefix plus unpadded
  base64url of that byte sequence.
"""

from __future__ import annotations

import base64
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from typing import Any

import msgspec
import zstandard as zstd
from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESSIV
from nacl.exceptions import CryptoError
from nacl.secret import Aead

from plap.errors import ErrorLevel, PlapError, PrivateError, PublicError
from plap.keyring import SealingKeyring, associated_data, purpose_label
from plap.responses.ingest.models import CallID, CompactionPayload, ReasoningPayload, Side

COMPACTION_PURPOSE = "responses.ingest.compaction"
REASONING_PURPOSE = "responses.ingest.reasoning"
CALL_ID_PURPOSE = "responses.ingest.call_id"
CALL_ID_PREFIX = "call_"
COMPACTION_PAYLOAD_FORMAT_VERSION = 4
REASONING_PAYLOAD_FORMAT_VERSION = 6
COMPACTION_PAYLOAD_TYPE = "compaction"
REASONING_PAYLOAD_TYPE = "reasoning"
CALL_ID_FORMAT_VERSION = 2
CALL_ID_HEADER_BYTES = 3
TAG_BYTES = 16
_CALL_ID_VERSION_SHIFT = 4
_CALL_ID_VERSION_MASK = 0xF0
_CALL_ID_RESERVED_MASK = 0x0C
_CALL_ID_CODEC_MASK = 0x03
_PACKED_META_RESERVED_MASK = 0xF8
_PACKED_META_UNUSED_MASK = 0x07
_BASE64URL_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
_BASE64URL_BY_CHAR = {char: index for index, char in enumerate(_BASE64URL_ALPHABET)}


def _tool_replay_error(*, reason: str, private_message: str, cause: BaseException | None = None) -> PlapError:
    return PlapError(
        public=PublicError(
            status_code=400,
            type="invalid_request_error",
            code="invalid_tool_replay",
            message="Tool replay data is invalid.",
            param="input",
        ),
        private=PrivateError(
            event="response.invalid_request",
            reason=reason,
            message=private_message,
            level=ErrorLevel.WARNING,
            cause=cause,
        ),
    )


def _compaction_replay_error(*, reason: str, private_message: str, cause: BaseException | None = None) -> PlapError:
    return PlapError(
        public=PublicError(
            status_code=400,
            type="invalid_request_error",
            code="invalid_compaction_replay",
            message="Compaction replay data is invalid.",
            param="input",
        ),
        private=PrivateError(
            event="response.invalid_request",
            reason=reason,
            message=private_message,
            level=ErrorLevel.WARNING,
            cause=cause,
        ),
    )


def _reasoning_replay_error(*, reason: str, private_message: str, cause: BaseException | None = None) -> PlapError:
    return PlapError(
        public=PublicError(
            status_code=400,
            type="invalid_request_error",
            code="invalid_reasoning_replay",
            message="Reasoning replay data is invalid.",
            param="input",
        ),
        private=PrivateError(
            event="response.invalid_request",
            reason=reason,
            message=private_message,
            level=ErrorLevel.WARNING,
            cause=cause,
        ),
    )


def _input_replay_error(*, reason: str, private_message: str, cause: BaseException | None = None) -> PlapError:
    return PlapError(
        public=PublicError(
            status_code=400,
            type="invalid_request_error",
            code="invalid_input_replay",
            message="Input replay items are invalid.",
            param="input",
        ),
        private=PrivateError(
            event="response.invalid_request",
            reason=reason,
            message=private_message,
            level=ErrorLevel.WARNING,
            cause=cause,
        ),
    )


def _aad(purpose: str) -> bytes:
    return purpose_label(purpose)


def _json_encode(value: object) -> bytes:
    return msgspec.json.encode(value, order="deterministic")


def _json_decode(value: bytes) -> object:
    try:
        return msgspec.json.decode(value)
    except msgspec.DecodeError as exc:
        raise _input_replay_error(
            reason="sealed_payload_invalid_json", private_message="sealed payload is not valid JSON", cause=exc
        ) from exc


def _b64url_encode(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).rstrip(b"=").decode()


def _b64url_decode(value: str) -> bytes:
    if not value:
        raise _input_replay_error(reason="sealed_payload_empty", private_message="sealed payload is empty")
    padding = "=" * (-len(value) % 4)
    try:
        return base64.urlsafe_b64decode(value + padding)
    except ValueError as exc:
        raise _input_replay_error(
            reason="sealed_payload_not_base64url", private_message="sealed payload is not base64url", cause=exc
        ) from exc


def _decode_upstream_id(value: bytes) -> str:
    if not value:
        raise _tool_replay_error(reason="upstream_tool_call_id_missing", private_message="upstream_tool_call_id is required")
    try:
        return value.decode()
    except UnicodeDecodeError as exc:
        raise _tool_replay_error(
            reason="upstream_tool_call_id_not_utf8", private_message="upstream_tool_call_id is not UTF-8", cause=exc
        ) from exc


@dataclass(frozen=True, slots=True)
class _Codec:
    code: int
    matches: Callable[[str], bool]
    encode: Callable[[str], bytes]
    decode: Callable[[bytes], str]


def _pack_fixed_width(values: list[int], *, bits_per_value: int) -> bytes:
    packed = bytearray()
    accumulator = 0
    count = 0
    for value in values:
        accumulator = (accumulator << bits_per_value) | value
        count += bits_per_value
        while count >= 8:
            count -= 8
            packed.append((accumulator >> count) & 0xFF)
    unused_bits = 0
    if count:
        unused_bits = 8 - count
        packed.append((accumulator << unused_bits) & 0xFF)
    return bytes([unused_bits]) + bytes(packed)


def _unpack_fixed_width(value: bytes, *, bits_per_value: int) -> list[int]:
    if len(value) < 2:
        raise _tool_replay_error(
            reason="function_call_id_packed_payload_too_short",
            private_message="packed function call id payload is too short",
        )
    meta = value[0]
    if meta & _PACKED_META_RESERVED_MASK:
        raise _tool_replay_error(
            reason="function_call_id_packed_meta_invalid",
            private_message="packed function call id metadata is invalid",
        )
    unused_bits = meta & _PACKED_META_UNUSED_MASK
    packed = value[1:]
    total_bits = len(packed) * 8 - unused_bits
    if total_bits <= 0 or total_bits % bits_per_value != 0:
        raise _tool_replay_error(
            reason="function_call_id_packed_payload_invalid",
            private_message="packed function call id payload is invalid",
        )
    payload = int.from_bytes(packed, byteorder="big")
    values: list[int] = []
    total_packed_bits = len(packed) * 8
    for offset in range(0, total_bits, bits_per_value):
        shift = total_packed_bits - bits_per_value - offset
        values.append((payload >> shift) & ((1 << bits_per_value) - 1))
    return values


def _matches_utf8(value: str) -> bool:
    _ = value
    return True


def _matches_ascii7(value: str) -> bool:
    return all(byte < 0x80 for byte in value.encode())


def _matches_base64url6(value: str) -> bool:
    return all(char in _BASE64URL_BY_CHAR for char in value)


def _encode_utf8(value: str) -> bytes:
    return value.encode()


def _encode_ascii7(value: str) -> bytes:
    return _pack_fixed_width(list(value.encode()), bits_per_value=7)


def _encode_base64url6(value: str) -> bytes:
    return _pack_fixed_width([_BASE64URL_BY_CHAR[char] for char in value], bits_per_value=6)


def _decode_ascii7(value: bytes) -> str:
    decoded = bytes(_unpack_fixed_width(value, bits_per_value=7))
    try:
        return decoded.decode("ascii")
    except UnicodeDecodeError as exc:
        raise _tool_replay_error(
            reason="upstream_tool_call_id_not_utf8",
            private_message="upstream_tool_call_id is not UTF-8",
            cause=exc,
        ) from exc


def _decode_base64url6(value: bytes) -> str:
    try:
        return "".join(_BASE64URL_ALPHABET[symbol] for symbol in _unpack_fixed_width(value, bits_per_value=6))
    except IndexError as exc:
        raise _tool_replay_error(
            reason="function_call_id_packed_payload_invalid",
            private_message="packed function call id payload is invalid",
            cause=exc,
        ) from exc


_CODECS: dict[int, _Codec] = {
    0: _Codec(code=0, matches=_matches_utf8, encode=_encode_utf8, decode=_decode_upstream_id),
    1: _Codec(code=1, matches=_matches_ascii7, encode=_encode_ascii7, decode=_decode_ascii7),
    2: _Codec(code=2, matches=_matches_base64url6, encode=_encode_base64url6, decode=_decode_base64url6),
}
_CODEC_PREFERENCE: tuple[_Codec, ...] = (_CODECS[2], _CODECS[1], _CODECS[0])


def _side_code(side_codes: Mapping[Side, int], side: Side) -> int:
    side_code = side_codes.get(side)
    if side_code is None or not 0 <= side_code <= 0xFFFF:
        raise _tool_replay_error(reason="invalid_function_call_side", private_message="invalid function call side")
    return side_code


def _side_name(side_codes: Mapping[Side, int], code: int) -> Side:
    for side, side_code in side_codes.items():
        if side_code == code:
            return side
    raise _tool_replay_error(reason="invalid_function_call_id_side", private_message="invalid function call id side")


def _decode_encoded_upstream_id(header: int, value: bytes) -> str:
    codec = header & _CALL_ID_CODEC_MASK
    try:
        return _CODECS[codec].decode(value)
    except KeyError as exc:
        raise _tool_replay_error(
            reason="unsupported_function_call_id_codec",
            private_message="unsupported function call id codec",
            cause=exc,
        ) from exc


def _compaction_to_json(value: CompactionPayload) -> dict[str, Any]:
    return {
        "version": COMPACTION_PAYLOAD_FORMAT_VERSION,
        "type": COMPACTION_PAYLOAD_TYPE,
        **value.to_primitive(),
    }


def _compaction_from_json(value: object) -> CompactionPayload:
    if not isinstance(value, dict):
        raise _compaction_replay_error(reason="compaction_payload_not_object", private_message="compaction payload must be an object")
    if value.get("version") != COMPACTION_PAYLOAD_FORMAT_VERSION or value.get("type") != COMPACTION_PAYLOAD_TYPE:
        raise _compaction_replay_error(reason="unsupported_compaction_payload", private_message="unsupported compaction payload")
    try:
        return CompactionPayload.from_primitive(
            {
                "id": value.get("id"),
                "durable": value.get("durable"),
                "sides": value.get("sides"),
            }
        )
    except (TypeError, ValueError) as exc:
        raise _compaction_replay_error(reason="compaction_payload_invalid", private_message=str(exc), cause=exc) from exc


def _reasoning_to_json(value: ReasoningPayload) -> dict[str, Any]:
    return {
        "version": REASONING_PAYLOAD_FORMAT_VERSION,
        "type": REASONING_PAYLOAD_TYPE,
        **value.to_primitive(),
    }


def _reasoning_from_json(value: object) -> ReasoningPayload:
    if not isinstance(value, dict):
        raise _reasoning_replay_error(reason="reasoning_payload_not_object", private_message="reasoning payload must be an object")
    if value.get("version") != REASONING_PAYLOAD_FORMAT_VERSION or value.get("type") != REASONING_PAYLOAD_TYPE:
        raise _reasoning_replay_error(reason="unsupported_reasoning_payload", private_message="unsupported reasoning payload")
    try:
        return ReasoningPayload.from_primitive(
            {
                "id": value.get("id"),
                "previous_reasoning_id": value.get("previous_reasoning_id"),
                "previous_compaction_id": value.get("previous_compaction_id"),
                "state": value.get("state"),
                "main": value.get("main"),
            }
        )
    except (TypeError, ValueError) as exc:
        raise _reasoning_replay_error(reason="reasoning_payload_invalid", private_message=str(exc), cause=exc) from exc


def _pack_call_id(value: CallID, *, side_codes: Mapping[Side, int]) -> bytes:
    if not value.upstream_tool_call_id:
        raise _tool_replay_error(reason="upstream_tool_call_id_missing", private_message="upstream_tool_call_id is required")
    side_code = _side_code(side_codes, value.side)
    for codec in _CODEC_PREFERENCE:
        if not codec.matches(value.upstream_tool_call_id):
            continue
        encoded_upstream_id = codec.encode(value.upstream_tool_call_id)
        header = (CALL_ID_FORMAT_VERSION << _CALL_ID_VERSION_SHIFT) | codec.code
        return b"".join(
            (
                bytes([header]),
                side_code.to_bytes(2, byteorder="big"),
                encoded_upstream_id,
            )
        )
    raise RuntimeError("at least one call id codec must match")


def _unpack_call_id(value: bytes, *, side_codes: Mapping[Side, int]) -> CallID:
    min_length = CALL_ID_HEADER_BYTES + 1
    if len(value) < min_length:
        raise _tool_replay_error(reason="function_call_id_plaintext_too_short", private_message="function call id plaintext is too short")
    header = value[0]
    version = (header & _CALL_ID_VERSION_MASK) >> _CALL_ID_VERSION_SHIFT
    if version != CALL_ID_FORMAT_VERSION:
        raise _tool_replay_error(reason="unsupported_function_call_id_version", private_message="unsupported function call id version")
    if header & _CALL_ID_RESERVED_MASK:
        raise _tool_replay_error(
            reason="function_call_id_reserved_bits_nonzero",
            private_message="function call id reserved bits must be zero",
        )
    side_code = int.from_bytes(value[1:CALL_ID_HEADER_BYTES], byteorder="big")
    return CallID(
        side=_side_name(side_codes, side_code),
        upstream_tool_call_id=_decode_encoded_upstream_id(header, value[CALL_ID_HEADER_BYTES:]),
    )


def _xchacha_seal(value: bytes, *, purpose: str, keyring: SealingKeyring) -> str:
    compressed = zstd.ZstdCompressor().compress(value)
    encrypted = Aead(keyring.active(purpose)).encrypt(compressed, _aad(purpose))
    return _b64url_encode(bytes(encrypted))


def _xchacha_open(value: str, *, purpose: str, keyring: SealingKeyring) -> bytes:
    encrypted = _b64url_decode(value)
    last_error: Exception | None = None
    for key in keyring.candidates(purpose):
        try:
            compressed = Aead(key).decrypt(encrypted, _aad(purpose))
            return zstd.ZstdDecompressor().decompress(compressed)
        except (CryptoError, ValueError, zstd.ZstdError) as exc:
            last_error = exc
    if purpose == COMPACTION_PURPOSE:
        raise _compaction_replay_error(
            reason="sealed_compaction_payload_open_failed",
            private_message=f"sealed {purpose} payload could not be opened",
            cause=last_error,
        ) from last_error
    if purpose == REASONING_PURPOSE:
        raise _reasoning_replay_error(
            reason="sealed_reasoning_payload_open_failed", private_message=f"sealed {purpose} payload could not be opened", cause=last_error
        ) from last_error
    raise _tool_replay_error(
        reason="sealed_tool_payload_open_failed", private_message=f"sealed {purpose} payload could not be opened", cause=last_error
    ) from last_error


def seal_compaction_payload(
    payload: CompactionPayload,
    *,
    keyring: SealingKeyring,
) -> str:
    return _xchacha_seal(
        _json_encode(_compaction_to_json(payload)),
        purpose=COMPACTION_PURPOSE,
        keyring=keyring,
    )


def open_compaction_payload(
    value: str,
    *,
    keyring: SealingKeyring,
) -> CompactionPayload:
    return _compaction_from_json(_json_decode(_xchacha_open(value, purpose=COMPACTION_PURPOSE, keyring=keyring)))


def seal_reasoning_payload(
    payload: ReasoningPayload,
    *,
    keyring: SealingKeyring,
) -> str:
    return _xchacha_seal(
        _json_encode(_reasoning_to_json(payload)),
        purpose=REASONING_PURPOSE,
        keyring=keyring,
    )


def open_reasoning_payload(
    value: str,
    *,
    keyring: SealingKeyring,
) -> ReasoningPayload:
    return _reasoning_from_json(_json_decode(_xchacha_open(value, purpose=REASONING_PURPOSE, keyring=keyring)))


def seal_call_id(
    value: CallID,
    *,
    keyring: SealingKeyring,
    side_codes: Mapping[Side, int],
) -> str:
    plaintext = _pack_call_id(value, side_codes=side_codes)
    ciphertext = AESSIV(keyring.active(CALL_ID_PURPOSE)).encrypt(
        plaintext,
        associated_data(CALL_ID_PURPOSE),
    )
    return CALL_ID_PREFIX + _b64url_encode(ciphertext)


def open_call_id(
    value: str,
    *,
    keyring: SealingKeyring,
    side_codes: Mapping[Side, int],
) -> CallID:
    if not value.startswith(CALL_ID_PREFIX):
        raise _tool_replay_error(reason="sealed_function_call_id_prefix_invalid", private_message="invalid sealed function call id prefix")
    payload = _b64url_decode(value[len(CALL_ID_PREFIX) :])
    if len(payload) <= TAG_BYTES:
        raise _tool_replay_error(
            reason="sealed_function_call_id_payload_too_short", private_message="sealed function call id payload is too short"
        )
    last_error: Exception | None = None
    for key in keyring.candidates(CALL_ID_PURPOSE):
        try:
            plaintext = AESSIV(key).decrypt(
                payload,
                associated_data(CALL_ID_PURPOSE),
            )
            return _unpack_call_id(plaintext, side_codes=side_codes)
        except (InvalidTag, PlapError) as exc:
            last_error = exc
    raise _tool_replay_error(
        reason="sealed_function_call_id_open_failed", private_message="sealed function call id could not be opened", cause=last_error
    ) from last_error
