from __future__ import annotations

from typing import Literal

from pydantic import Field, field_validator

from plap.responses.contracts.base import (
    Metadata,
    StrictModel,
    _validate_metadata,
)
from plap.responses.contracts.items import (
    InputItemsPageItem,
    RequestInputItem,
    ResponseOutputItem,
)
from plap.responses.contracts.requests import (
    ConversationReference,
    PromptReference,
    ReasoningConfig,
    ServiceTier,
)
from plap.responses.contracts.tools import (
    ResponseTextConfig,
    SupportedTool,
    ToolChoice,
)


class ResponseUsageInputTokensDetails(StrictModel):
    cached_tokens: int = Field(ge=0, description="Input tokens retrieved from prompt cache.")


class ResponseUsageOutputTokensDetails(StrictModel):
    reasoning_tokens: int = Field(ge=0, description="Reasoning tokens generated.")


class ResponseUsage(StrictModel):
    input_tokens: int = Field(ge=0, description="Number of input tokens consumed.")
    input_tokens_details: ResponseUsageInputTokensDetails = Field(
        description="Breakdown of input tokens, such as cached tokens.",
    )
    output_tokens: int = Field(ge=0, description="Number of output tokens generated.")
    output_tokens_details: ResponseUsageOutputTokensDetails = Field(
        description="Breakdown of output tokens, such as reasoning tokens.",
    )
    total_tokens: int = Field(ge=0, description="Input plus output token count.")


type ResponseErrorCode = Literal[
    "server_error",
    "rate_limit_exceeded",
    "invalid_prompt",
    "vector_store_timeout",
    "invalid_image",
    "invalid_image_format",
    "invalid_base64_image",
    "invalid_image_url",
    "image_too_large",
    "image_too_small",
    "image_parse_error",
    "image_content_policy_violation",
    "invalid_image_mode",
    "image_file_too_large",
    "unsupported_image_media_type",
    "empty_image_file",
    "failed_to_download_image",
    "image_file_not_found",
]


class ResponseError(StrictModel):
    code: ResponseErrorCode = Field(description="Machine-readable error code.")
    message: str = Field(description="Human-readable error message.")


type ResponseStatus = Literal[
    "queued",
    "in_progress",
    "completed",
    "failed",
    "cancelled",
    "incomplete",
]


class ResponseIncompleteDetails(StrictModel):
    reason: Literal["max_output_tokens", "content_filter"] | None = Field(
        default=None,
        description="Reason why the response status is incomplete.",
    )


class ResponseObject(StrictModel):
    # background: bool | None = Field(
    #     default=None, description="Whether it ran in background mode."
    # )
    completed_at: float | None = Field(
        default=None,
        description="Unix timestamp in seconds when generation completed.",
    )
    conversation: ConversationReference | None = Field(
        default=None,
        description="Conversation associated with this response, when present.",
    )
    created_at: float = Field(description="Unix timestamp in seconds when created.")
    error: ResponseError | None = Field(
        default=None,
        description="Embedded generation error when the response failed.",
    )
    id: str = Field(description="Unique response ID.")
    incomplete_details: ResponseIncompleteDetails | None = Field(
        default=None,
        description="Details about why the response is incomplete.",
    )
    instructions: str | list[RequestInputItem] | None = Field(
        default=None,
        description="Instructions used for this response.",
    )
    max_output_tokens: int | None = Field(
        default=None,
        ge=1,
        description="Configured upper bound for output tokens.",
    )
    max_tool_calls: int | None = Field(
        default=None,
        ge=1,
        description="Configured maximum total built-in tool calls.",
    )
    metadata: Metadata | None = Field(
        default=None,
        description="Metadata attached by the caller.",
    )
    model: str | None = Field(default=None, description="Model ID used.")
    object: Literal["response"] = Field(
        default="response",
        description="Object type discriminator; always `response`.",
    )
    output: list[ResponseOutputItem] = Field(description="Ordered output items generated by the model.")
    parallel_tool_calls: bool | None = Field(
        default=None,
        description="Whether parallel tool calls were allowed.",
    )
    previous_response_id: str | None = Field(
        default=None,
        description="Previous response ID used for continuation.",
    )
    prompt: PromptReference | None = Field(
        default=None,
        description="Prompt template reference used for the response.",
    )
    prompt_cache_key: str | None = Field(
        default=None,
        description="Prompt cache key used for this response.",
    )
    reasoning: ReasoningConfig | None = Field(
        default=None,
        description="Reasoning configuration used.",
    )
    safety_identifier: str | None = Field(
        default=None,
        description="Safety identifier attached to the request.",
    )
    service_tier: ServiceTier | None = Field(
        default=None,
        description="Service tier requested for processing.",
    )
    status: ResponseStatus = Field(description="Response generation status.")
    temperature: float | None = Field(default=None, ge=0, le=2, description="Sampling temperature used.")
    text: ResponseTextConfig | None = Field(
        default=None,
        description="Text/structured-output configuration used.",
    )
    tool_choice: ToolChoice | None = Field(default=None, description="Tool choice used.")
    tools: list[SupportedTool] | None = Field(
        default=None,
        description="Supported tools made available to the model.",
    )
    top_logprobs: int | None = Field(
        default=None,
        ge=0,
        le=20,
        description="Requested number of token logprobs.",
    )
    top_p: float | None = Field(default=None, ge=0, le=1, description="Nucleus sampling value used.")
    truncation: Literal["auto", "disabled"] | None = Field(
        default=None,
        description="Truncation mode used.",
    )
    usage: ResponseUsage | None = Field(
        default=None,
        description="Token usage for the response.",
    )
    user: str | None = Field(default=None, description="Legacy user identifier.")

    @field_validator("metadata")
    @classmethod
    def validate_metadata(cls, value: Metadata | None) -> Metadata | None:
        return _validate_metadata(value)


class ResponseDeleted(StrictModel):
    deleted: Literal[True] = Field(description="Deletion marker; always true.")
    id: str = Field(description="Deleted response ID.")
    object: Literal["response"] = Field(
        default="response",
        description="Object type discriminator; OpenAI documents `response` here.",
    )


class CompactedResponseObject(StrictModel):
    created_at: int = Field(description="Unix timestamp in seconds when created.")
    id: str = Field(description="Unique compaction response ID.")
    object: Literal["response.compaction"] = Field(
        default="response.compaction",
        description="Object type discriminator for compacted responses.",
    )
    output: list[ResponseOutputItem] = Field(description="Compacted output items from the compaction pass.")
    usage: ResponseUsage = Field(description="Token usage for the compaction request.")


class InputItemsPage(StrictModel):
    data: list[InputItemsPageItem] = Field(description="Page of supported input items.")
    first_id: str | None = Field(default=None, description="First item ID in this page.")
    has_more: bool = Field(description="Whether another page exists after this one.")
    last_id: str | None = Field(default=None, description="Last item ID in this page.")
    object: Literal["list"] = Field(
        default="list",
        description="Object type discriminator for list responses.",
    )
